### PR TITLE
[QA PASSED] [HOTFIX] Fix multiple tags

### PR DESCRIPTION
**Pull request by kimoycatayas**
Screenshot 2023-08-28 at 3 59 31 PM
Screenshot 2023-08-28 at 4 00 11 PM
Screenshot 2023-08-28 at 4 00 23 PM

### CODE REVIEW

**Review by jonmediajel — CHANGES_REQUESTED** [review]
This is still duplicating on staging

Tested staging branch

image

**Comment by ZeeLiger** [comment]
Did `git checkout ekc-multiple-tags`
then `git rebase main`
then resolved the conflicts

Tested locally and the tags are not duplicating
image

image

image

**Comment by SeanRizarre** [comment]
Tested it and it's not duplicating.

image
image
image
image
image

**Review by pacholoamit — APPROVED** [review]
Tested and works!

**Pull request merged**
